def create_ask_price_list(sheet,max_row):
    'function to create a list with all ask prices of each car with in a month'
    ask_price_list = []
    for i in range(2,max_row+1):
        ask_price_list.append(sheet.cell(i,7).value)
    return ask_price_list

def create_sell_price_list(sheet,max_row):
    'function to create a list with all sell prices of each car with in a month'
    sell_price_list = []
    for i in range(2,max_row+1):
        sell_price_list.append(sheet.cell(i,8).value)
    return sell_price_list

def add_ask_prices(ask_price_list):
    'function to add all ask prices'
    total_ask_price = 0
    for i in range(len(ask_price_list)):
        total_ask_price += ask_price_list[i]
    return total_ask_price

def add_sell_prices(sell_price_list):
    'function to add all sell prices'
    total_sell_price = 0
    for i in range(len(sell_price_list)):
        total_sell_price += sell_price_list[i]
    return total_sell_price

def print_monthly_profit(total_sell_price,total_ask_price):
    'function to print the monthly profit generated by the sales department'
    monthly_profit_value = total_sell_price - total_ask_price
    return monthly_profit_value